* Table of Contents                                            :TOC:noexport:
- [[#jinlor-themes][Jinlor Themes]]
  - [[#installation][Installation]]
  - [[#usage][Usage]]
  - [[#license][License]]

* Jinlor Themes

Jinlor Themes is a collection of colorful, legible Emacs themes built
on [[https://github.com/protesilaos/modus-themes][Modus Themes]].  Its palettes are inspired by architecture,
characters, and imagined worlds.

| Name           | Description                                    |
|----------------+------------------------------------------------|
| jinlor-elysia  | To Romantic Unfailing Elysia                   |
| jinlor-eva-00  | Evangelion Unit-00 and Rei Ayanami (light)     |
| jinlor-eva-01  | Evangelion Unit-01 and Shinji Ikari            |
| jinlor-eva-02  | Evangelion Unit-02 and Asuka Shikinami Langley |
| jinlor-palace  | The Palace Museum                              |

** Installation

Jinlor requires Emacs 30.1 or later and Modus Themes 5.3.0 or later.

1. Clone this repository

#+begin_src bash-ts
git clone https://github.com/dalugm/jinlor.el.git
#+end_src

2. Add =jinlor= to load-path.

#+begin_src elisp
(add-to-list 'load-path (expand-file-name "path/to/jinlor.el"))
(require 'jinlor)
#+end_src

** Usage

#+begin_src elisp
(load-theme 'jinlor-eva-01 t)
#+end_src

** License

Jinlor Themes is released under the GNU General Public License,
version 3 or any later version.  See [[file:LICENSE][LICENSE]].
